/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBCOMM.h"
#include "USBCOMM_audio.h"
#include "USBCOMM_cdc.h"
#include "USBCOMM_hid.h"
#include "USBCOMM_midi.h"
#include "USBCOMM_pvt.h"
#include "USBCOMM_cydmac.h"
#include "USBCOMM_msc.h"
#include "AnalogClock.h"
#include "VAnalogOut_aliases.h"
#include "VAnalogOut.h"
#include "WaveGen.h"
#include "WaveFormSelect_aliases.h"
#include "WaveFormSelect.h"
#include "WaveFormReader.h"
#include "USBCOMM_Dm_aliases.h"
#include "USBCOMM_Dm.h"
#include "USBCOMM_Dp_aliases.h"
#include "USBCOMM_Dp.h"
#include "WaveGen_Wave1_DMA_dma.h"
#include "WaveGen_Wave2_DMA_dma.h"
#include "WaveGen_VDAC8.h"
#include "WaveFormReader_IRQ.h"
#include "WaveFormReader_theACLK.h"
#include "WaveFormReader_Bypass_aliases.h"
#include "WaveFormReader_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

